toolchain_type for macos x86-64 is missing (#22)
Using rules_pkl on macos x86-64 fails since there is no matching
toolchain for the platform
```
$ pwd
/Users/rtough/devel/rules_pkl
$ bazel test //...
INFO: Invocation ID: c3f60495-2ebd-4f56-90e1-c7b9fb53c0f5
ERROR: /Users/rtough/devel/rules_pkl/test/pkl_test/BUILD.bazel:3:9: While resolving toolchains for target //test/pkl_test:pkl_test_1: No matching toolchains found for types //pkl:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='//pkl:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: Analysis of target '//test/pkl_test:pkl_test_1' failed; build aborted:
INFO: Elapsed time: 0.281s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (24 packages loaded, 244 targets configured)
ERROR: Couldn't start the build. Unable to run tests
```