Upgrade `gazelle` to v0.35.0
We can't upgrade to Bazel 7 without this bump, as we'll see the
following error:

```
❯ bazel test //...
INFO: Invocation ID: 4e685f90-2c73-4536-9983-ef261d4f6da8
ERROR: /private/var/tmp/_bazel_kushal/cb69cc106c9cff5a6ac34d1390aa8454/external/rules_go~0.38.1/BUILD.bazel:71:16: in (an implicit dependency) attribute of go_context_data rule @@rules_go~0.38.1//:go_context_data: in $whitelist_function_transition attribute of go_context_data rule @@rules_go~0.38.1//:go_context_data: package group '@@bazel_tools//tools/whitelists/function_transition_whitelist:function_transition_whitelist' is misplaced here (they are only allowed in the visibility attribute)
ERROR: /private/var/tmp/_bazel_kushal/cb69cc106c9cff5a6ac34d1390aa8454/external/rules_go~0.38.1/BUILD.bazel:71:16: Analysis of target '@@rules_go~0.38.1//:go_context_data' failed
INFO: Repository rules_jvm_external~5.3~maven~org_graalvm_truffle_truffle_api_22_3_1 instantiated at:
  <builtin>: in <toplevel>
Repository rule http_file defined at:
  /private/var/tmp/_bazel_kushal/cb69cc106c9cff5a6ac34d1390aa8454/external/bazel_tools/tools/build_defs/repo/http.bzl:472:28: in <toplevel>
INFO: Repository _main~pkl~pkl-cli-linux-arm64 instantiated at:
  <builtin>: in <toplevel>
Repository rule http_file defined at:
  /private/var/tmp/_bazel_kushal/cb69cc106c9cff5a6ac34d1390aa8454/external/bazel_tools/tools/build_defs/repo/http.bzl:472:28: in <toplevel>
INFO: Repository rules_jvm_external~5.3~maven~com_apple_pkl_pkl_tools_0_24_6 instantiated at:
  <builtin>: in <toplevel>
Repository rule http_file defined at:
  /private/var/tmp/_bazel_kushal/cb69cc106c9cff5a6ac34d1390aa8454/external/bazel_tools/tools/build_defs/repo/http.bzl:472:28: in <toplevel>
Use --verbose_failures to see the command lines of failed build steps.
ERROR: Analysis of target '//:gazelle_bin' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.823s, Critical Path: 0.36s
INFO: 26 processes: 13 internal, 13 darwin-sandbox.
ERROR: Build did NOT complete successfully
//test/pkl_library:test_transitive_sources                            NO STATUS
//test/pkl_test:pkl_test_1                                            NO STATUS
//test/pkl_test:pkl_test_2                                            NO STATUS
//test/toolchain:test_current_toolchain_at_build_time                 NO STATUS
//test/toolchain:test_current_toolchain_at_runtime                    NO STATUS
```